require('dotenv').config();
const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const userRoutes = require('./routes/user.routes');
const universitiesRoutes = require('./routes/universities.routes');
const followRoutes = require('./routes/follow_ups.routes');
const teachersRoutes = require('./routes/teachers.routes');
const studentRoutes = require('./routes/student.routes');
const vacantRoutes = require('./routes/vacant.routes');
const businessesRoutes = require('./routes/businesses.routes');
const supervisorsRoutes = require('./routes/supervisors.routes');
const practicesRoutes = require('./routes/practices.routes');
const earringsRoutes = require('./routes/earrings.routes');
const evaluationsRoutes = require('./routes/evaluations.routes');
const modalitiesRoutes = require('./routes/modalities.routes');
const timeModalitiesRoutes = require('./routes/time_modalities.routes');
const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use('/api/follow-ups', followRoutes);
app.use('/api/auth', userRoutes);
app.use('/api/teachers', teachersRoutes);
app.use('/api/student', studentRoutes);
app.use('/api/vacants', vacantRoutes);
app.use('/api/businesses', businessesRoutes);
app.use('/api/supervisors', supervisorsRoutes);
app.use('/api/practices', practicesRoutes);
app.use('/api/universities', universitiesRoutes);
app.use('/api/evaluations', evaluationsRoutes);
app.use('/api/earrings', earringsRoutes);
app.use('/api/modalities', modalitiesRoutes);
app.use('/api/timeModalities', timeModalitiesRoutes);
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
